# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sbuddy-dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_404f3969112f42b88d4f8314a77fd225 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_51f0356e7c164a5bbcac9b619572f5c2 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_404f3969112f42b88d4f8314a77fd225 }}/arcgo/sbuddy-client:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sbuddy-dev'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_6fc9830fc6de48918215b89868c6b270 }}
          images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_404f3969112f42b88d4f8314a77fd225 }}/arcgo/sbuddy-client:${{ github.sha }}'
