name: CI/CD for dev branch

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up SSH
        run: |
          touch sbuddy_dev.pem
          echo -n "${{ secrets.DEV_SERVER_PRIVATE_KEY }}" > sbuddy_dev.pem
          chmod 600 sbuddy_dev.pem
          
      - name: Connect to Azure sbuddy-dev-server and deploy
        uses: appleboy/ssh-action@master
        with: 
          script: ssh -i sbuddy_dev.pem ${{secrets.DEV_SERVER_USERNAME}}@${{secrets.DEV_SERVER_IP}} -o "StrictHostKeyChecking=no" && sudo apt-get install -y nodejs && cd /home/azureuser/sbuddy && git pull && cd client && npm install && npm run && cd .. && cd server && npm install && npm run
