# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Submit docker images of client and server to docker.io

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push client container image to registry
        uses: docker/build-push-action@v3
        with:
          context: ./client
          push: true
          tags: index.docker.io/${{ secrets.DOCKER_HUB_USER }}/sbuddy-client:latest
          file: ./client/Dockerfile

      - name: Build and push server container image to registry
        uses: docker/build-push-action@v3
        with:
          context: ./server
          push: true
          tags: index.docker.io/${{ secrets.DOCKER_HUB_USER }}/sbuddy-server:latest
          file: ./server/Dockerfile
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}